apiVersion: v1
kind: Pod
metadata:
  name: "{{ include "webanalysis.fullname" . }}-webanalysis-connection"
  labels:
    {{- include "webanalysis.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": webanalysis
spec:
  containers:
    - name: wget
      image: busybox
      command: ['wget']
      args: ['{{ include "webanalysis.fullname" . }}:{{ .Values.service.port }}']
  restartPolicy: Never
